Repository PaddlePaddle/awesome-DeepLearning, pull requests merged in 2022-03, with the labels that each got.

#839 #d2l add 11_10 11_11 13_1 13_2 14_7
  15_2 sentiment-analysis-rnn.md
  Dive-into-DL-paddlepaddle/docs/11_optimization_algorithm/11_10 adam.md
  Dive-into-DL-paddlepaddle/docs/11_optimization_algorithm/11_11 lr-scheduler.md
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/13_1 image-augmentation.md
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/13_2 fine-tuning.md
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/img/cat1.jpg
  Dive-into-DL-paddlepaddle/docs/14_natural-language-processing-pretraining/14.7 similarity-analogy.md
  Dive-into-DL-paddlepaddle/docs/15_natural-language-processing-applications/15_2 sentiment-analysis-rnn.md
Labels: d2l chap11.10/11.11/13.1/13.2/14.7, d2l chap15.2

#828 #d2l 12.1 12.2 12.3 12.5 12.6 14.8 14.10
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.1.ipynb
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.1.md
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.2.ipynb
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.2.md
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.3.ipynb
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.3.md
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.5.ipynb
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.5.md
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.6.ipynb
  Dive-into-DL-paddlepaddle/docs/12_computational-performance/12.6.md
  Dive-into-DL-paddlepaddle/docs/14_chapter_natural-language-processing-pretraining/14.10.ipynb
  Dive-into-DL-paddlepaddle/docs/14_chapter_natural-language-processing-pretraining/14.10.md
  Dive-into-DL-paddlepaddle/docs/14_chapter_natural-language-processing-pretraining/14.8.ipynb
  Dive-into-DL-paddlepaddle/docs/14_chapter_natural-language-processing-pretraining/14.8.md
Labels: d2l chap12.1

#817 #d2l add chapter 8.2 and fix temporary path in d2l
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/13.10.md
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/13.12.md
  Dive-into-DL-paddlepaddle/docs/14_chapter_natural-language-processing-pretraining/14.9.md
  Dive-into-DL-paddlepaddle/docs/2_Preparatory-knowledge/2.6.md
  Dive-into-DL-paddlepaddle/docs/5_deep-learning-computation/5.2.md
  Dive-into-DL-paddlepaddle/docs/5_deep-learning-computation/5.5.md
  Dive-into-DL-paddlepaddle/docs/8_recurrent-neural-networks/8.2.md
  Dive-into-DL-paddlepaddle/docs/8_recurrent-neural-networks/8.3.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/9.5.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/9.6.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/9.8.md
  Dive-into-DL-paddlepaddle/docs/d2l/paddle.py
Labels: d2l chap8.2/8.3/13.10/13.12, d2l chap9.5/9.8/9.6, d2l chap2.6

#826 #d2l
  Dive-into-DL-paddlepaddle/docs/13_computer-vision/13.9 semantic-segmentation-and-dataset.md
  Dive-into-DL-paddlepaddle/docs/8_recurrent-neural-networks/8.1sequence.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/bi-rnn.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/deep-rnn.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/gru.md
  Dive-into-DL-paddlepaddle/docs/9_recurrent-modern/lstm.md
Labels: d2l chap8.1/9.1/9.2/9.3/9.4
